/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "Pufferfish/Application/mcu_pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SensorMeasurements, SensorMeasurements, AUTO)


PB_BIND(CycleMeasurements, CycleMeasurements, AUTO)


PB_BIND(Parameters, Parameters, AUTO)


PB_BIND(ParametersRequest, ParametersRequest, AUTO)


PB_BIND(Range, Range, AUTO)


PB_BIND(AlarmLimits, AlarmLimits, AUTO)


PB_BIND(AlarmLimitsRequest, AlarmLimitsRequest, AUTO)


PB_BIND(LogEvent, LogEvent, AUTO)


PB_BIND(ExpectedLogEvent, ExpectedLogEvent, AUTO)


PB_BIND(NextLogEvents, NextLogEvents, AUTO)


PB_BIND(ActiveLogEvents, ActiveLogEvents, AUTO)


PB_BIND(AlarmMute, AlarmMute, AUTO)


PB_BIND(AlarmMuteRequest, AlarmMuteRequest, AUTO)


PB_BIND(MCUPowerStatus, MCUPowerStatus, AUTO)


PB_BIND(BackendConnections, BackendConnections, AUTO)


PB_BIND(ScreenStatusRequest, ScreenStatusRequest, AUTO)


PB_BIND(ScreenStatus, ScreenStatus, AUTO)


PB_BIND(Ping, Ping, AUTO)


PB_BIND(Announcement, Announcement, AUTO)







#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

