"""Script to test time complexity of crc and hash functions."""

import hashlib
import os
import time
import sys
from crcmod import predefined as predefinedcrc
from typing import Optional

from ventserver.util import crc


def gen_data(low: int = 32, high: int = 64,
    increment: int = 2, multiplier: bool = True,
    additionals: Optional[list] = None
):
    """Generate a dictionary of random bytes of given size."""
    
    assert (high > low), "high should be greater than low." 
    data: dict = dict()
    while low <= high:
        data[low] = bytes(os.urandom(low))
        if multiplier:
            low *= increment
        else:
            low += increment

    if additionals:
        assert (isinstance(additionals,list)), "additionals should be a list instance."
        for each in additionals:
            data[each] = bytes(os.urandom(each))

    return data


def calculate_timings(data: list, functions: dict, 
    iterations: int = 1000
):
    """Calculate the time complexity for given hash functions and data."""
    
    print(f"Processing for {iterations} iterations.")
    timings = {_func:list() for _func in functions}
    timings_avg = {_func:list() for _func in functions}
    
    for each in data:
        for func in functions:
            if 'crc' in func:
                test_time = list()
                for i in range(iterations):
                    start = time.perf_counter()
                    _ = functions[func](each)
                    end = time.perf_counter()
                    test_time.append(end - start)
                timings[func].append(sum(test_time))
                timings_avg[func].append(sum(test_time)/len(test_time))
            else:
                test_time = list()
                for i in range(iterations):
                    hash_func = hashlib.new(func)
                    start = time.perf_counter()
                    hash_func.update(each)
                    _ = hash_func.digest()
                    end = time.perf_counter()
                    test_time.append(end - start)
                    del hash_func
                timings[func].append(sum(test_time))
                timings_avg[func].append(sum(test_time)/len(test_time))
        print(f"Completed {len(each)}")

    return timings, timings_avg

def print_timings(timings: dict, timings_avg: dict, data: dict):
    """Print the time generated by calculate_timings."""
    
    print("Time taken in seconds total(avg))...")
    bytes_header: str = "\t\t\t".join([str(key) for key in data.keys()])
    print("bytes\t\t" + bytes_header)

    for func in timings:
        timings_ = "\t".join(["{0:f}({1:f})".format(total, avg) for \
         total, avg in zip(timings[func], timings_avg[func])])
        print(f"{func}\t\t{timings_}")

def main():

    functions: dict = {
        'mod_crc': lambda data: crc.compute_reflected_crc(data, crc.CRC32C_REFLECTED_TABLE),
        'pf_crc': predefinedcrc.mkCrcFun('crc-32c'),
        'sha1': hashlib.sha1,
        'md5': hashlib.md5,
        'blake2b': hashlib.blake2b,
        'blake2s': hashlib.blake2s
    }

    low: int = 32
    high: int = 1024
    increment: int = 2
    iterations: list = [1000, 5000, 10000, 15000]
    data: dict = gen_data(low = low, high = high, increment = increment, additionals = [20])
    
    # print actual size of data objects in the memory
    print("Actual sizes of generated chunks ...")
    for each in data.values():
        print(f"{len(each)} bytes: {sys.getsizeof(each)}")

    # measure timings
    for iteration in iterations:
        timings_total, timings_avg = calculate_timings(data.values(), \
            functions, iterations=iteration)

        print_timings(timings_total, timings_avg, data) 

if __name__ == '__main__':
    main()
